# Generated by Django 2.1.7 on 2019-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_user',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extended_user',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
    ]
