# Generated by Django 2.1.7 on 2019-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('creator', models.IntegerField()),
                ('addressed_by', models.IntegerField()),
                ('resolved_by', models.IntegerField()),
                ('read_by', models.CharField(max_length=100)),
                ('queue_number', models.IntegerField()),
                ('dateTime_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=60)),
                ('resolved', models.IntegerField(default=0)),
                ('read', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=256)),
                ('user', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('thread_queue_number', models.IntegerField()),
                ('author', models.IntegerField()),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
                ('dateTime_created', models.DateTimeField()),
            ],
        ),
    ]
