# Generated by Django 2.1.7 on 2019-04-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_creation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('creator', models.CharField(max_length=20)),
                ('addressed_by', models.CharField(max_length=20)),
                ('resolved_by', models.CharField(max_length=20)),
                ('read_by', models.CharField(max_length=100)),
                ('queue_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
