# Generated by Django 2.1.7 on 2019-04-07 14:28

from django.db import migrations

"""
Creating empty migration files
Source: https://docs.djangoproject.com/es/2.1/topics/migrations/#data-migrations
"""

def add_first_row(apps, schema_editor):
    All_Tickets = apps.get_model('ticket_creation', 'All_Tickets')
    a = All_Tickets(size=0, creator="boi", addressed_by="big boi", resolved_by="biggest boi", read_by="biggestest boi(?)", queue_number=0)
    a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_creation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_first_row),
    ]
